# Generated by Django 2.2.14 on 2020-07-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinformation',
            name='RamPercentage',
            field=models.FloatField(),
        ),
    ]
